# generate_secrets.cmake — Decrypt SOPS secrets at configure time and
# write C headers into the build tree so plaintext never lands in the
# source tree.
#
# Expected variables (set by the caller before include()):
#   SOPS_FILE   — path to the encrypted .sops.yaml
#   OUT_DIR     — directory under which secrets/ headers are written
#
# If sops is not installed or the encrypted file is missing, placeholder
# headers are generated so that the build still compiles (useful for CI
# and test_build_freezer.sh).

file(MAKE_DIRECTORY "${OUT_DIR}/secrets")

set(_thread_creds "${OUT_DIR}/secrets/thread_creds.h")

# ---------------------------------------------------------------------------
# Try to decrypt
# ---------------------------------------------------------------------------
set(_decrypted "")
find_program(SOPS_BIN sops)

if(SOPS_BIN AND EXISTS "${SOPS_FILE}")
    execute_process(
        COMMAND "${SOPS_BIN}" --decrypt "${SOPS_FILE}"
        OUTPUT_VARIABLE _raw
        RESULT_VARIABLE _rc
        ERROR_VARIABLE  _err
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT _rc EQUAL 0)
        message(WARNING "sops decrypt failed (rc=${_rc}): ${_err}\n"
                        "Falling back to placeholder secrets.")
    else()
        # sops wraps plaintext in "data: |" YAML — extract indented lines
        string(REGEX MATCHALL "[^\n]+" _lines "${_raw}")
        foreach(_line ${_lines})
            string(REGEX MATCH "^[ \t]+(.+)" _m "${_line}")
            if(_m)
                string(STRIP "${CMAKE_MATCH_1}" _stripped)
                list(APPEND _decrypted "${_stripped}")
            endif()
        endforeach()
    endif()
else()
    if(NOT SOPS_BIN)
        message(STATUS "sops not found — generating placeholder secrets")
    else()
        message(STATUS "${SOPS_FILE} not found — generating placeholder secrets")
    endif()
endif()

# ---------------------------------------------------------------------------
# Helper: look up a KEY=VALUE pair from the decrypted lines
# ---------------------------------------------------------------------------
macro(get_val _key _out)
    set(${_out} "")
    foreach(_entry ${_decrypted})
        string(REGEX MATCH "^${_key}=(.+)" _m "${_entry}")
        if(_m)
            set(${_out} "${CMAKE_MATCH_1}")
        endif()
    endforeach()
endmacro()

# ---------------------------------------------------------------------------
# Helper: convert a hex string to a C byte-array initializer
#   hex_to_c_array("1122334455667788" 8 _out)  →  "0x11, 0x22, …"
# ---------------------------------------------------------------------------
function(hex_to_c_array _hex _nbytes _out)
    set(_result "")
    math(EXPR _last "(${_nbytes} - 1) * 2")
    foreach(_i RANGE 0 ${_last} 2)
        string(SUBSTRING "${_hex}" ${_i} 2 _byte)
        if(_result)
            string(APPEND _result ", ")
        endif()
        string(APPEND _result "0x${_byte}")
    endforeach()
    set(${_out} "${_result}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# Extract values (or fall back to placeholders)
# ---------------------------------------------------------------------------
if(_decrypted)
    get_val("THREAD_NETWORK_NAME"   _NETWORK_NAME)
    get_val("THREAD_CHANNEL"        _CHANNEL)
    get_val("THREAD_PAN_ID"         _PAN_ID)
    get_val("THREAD_EXT_PAN_ID"     _EXT_PAN_HEX)
    get_val("THREAD_NETWORK_KEY"    _NET_KEY_HEX)
    get_val("THREAD_MESH_LOCAL_PREFIX" _MESH_PREFIX)
    hex_to_c_array("${_EXT_PAN_HEX}" 8  _EXT_PAN_C)
    hex_to_c_array("${_NET_KEY_HEX}" 16 _NET_KEY_C)
else()
    set(_NETWORK_NAME "DummyThread")
    set(_CHANNEL      "15")
    set(_PAN_ID       "0x1234")
    set(_EXT_PAN_C    "0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88")
    set(_NET_KEY_C    "0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff")
    set(_MESH_PREFIX  "fd11:22::/64")
endif()

# ---------------------------------------------------------------------------
# Write thread_creds.h
# ---------------------------------------------------------------------------
file(WRITE "${_thread_creds}"
"#ifndef THREAD_CREDS_H
#define THREAD_CREDS_H

/* Auto-generated by cmake/generate_secrets.cmake — DO NOT EDIT. */

#include <stdint.h>

#define THREAD_NETWORK_NAME   \"${_NETWORK_NAME}\"
#define THREAD_CHANNEL        ${_CHANNEL}
#define THREAD_PAN_ID         ${_PAN_ID}

static const uint8_t THREAD_EXT_PAN_ID[8] = {
    ${_EXT_PAN_C}
};

static const uint8_t THREAD_NETWORK_KEY[16] = {
    ${_NET_KEY_C}
};

#define THREAD_MESH_LOCAL_PREFIX  \"${_MESH_PREFIX}\"

#endif /* THREAD_CREDS_H */
")

message(STATUS "Generated ${_thread_creds}")
