#!/usr/bin/env bash
#
# Decrypt secrets/thread_auth.sops.yaml and generate include/secrets/thread_auth.h
#
# Usage (from devices/freezer-temp-sensor/):
#   bash scripts/decrypt_secrets.sh
#
# Requires: sops, age key at ~/.config/sops/age/keys.txt
#
# The generated header defines:
#   THREAD_NETWORK_NAME  (string)
#   THREAD_CHANNEL       (integer)
#   THREAD_PAN_ID        (hex integer, e.g. 0x1234)
#   THREAD_EXT_PAN_ID    (uint8_t[8] array)
#   THREAD_NETWORK_KEY   (uint8_t[16] array)
#   THREAD_MESH_LOCAL_PREFIX (string)
#   THREAD_HA_BASE_URL   (string)
#   THREAD_HA_API_KEY    (string)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVICE_DIR="$(dirname "$SCRIPT_DIR")"
SOPS_FILE="$DEVICE_DIR/secrets/thread_auth.sops.yaml"
OUT_FILE="$DEVICE_DIR/include/secrets/thread_auth.h"

if [[ ! -f "$SOPS_FILE" ]]; then
    echo "ERROR: $SOPS_FILE not found."
    echo "Create it with:"
    echo "  sops --encrypt --age \$(age-keygen -y ~/.config/sops/age/keys.txt) auth.txt > secrets/thread_auth.sops.yaml"
    exit 1
fi

echo "Decrypting $SOPS_FILE ..."
# sops wraps plaintext files under a "data: |" YAML key; strip that wrapper
# so we get raw KEY=VALUE lines.
DECRYPTED=$(sops --decrypt "$SOPS_FILE" | awk '/^ /{gsub(/^[[:space:]]+/, ""); print}')

mkdir -p "$(dirname "$OUT_FILE")"

# Helper: extract value for a key from KEY=VALUE lines
get_val() {
    echo "$DECRYPTED" | grep "^${1}=" | cut -d= -f2-
}

NETWORK_NAME=$(get_val "THREAD_NETWORK_NAME")
CHANNEL=$(get_val "THREAD_CHANNEL")
PAN_ID=$(get_val "THREAD_PAN_ID")
EXT_PAN_ID_HEX=$(get_val "THREAD_EXT_PAN_ID")   # e.g. 1122334455667788
NETWORK_KEY_HEX=$(get_val "THREAD_NETWORK_KEY")  # e.g. 00112233445566778899aabbccddeeff
MESH_LOCAL_PREFIX=$(get_val "THREAD_MESH_LOCAL_PREFIX")
HA_BASE_URL=$(get_val "THREAD_HA_BASE_URL")
HA_API_KEY=$(get_val "THREAD_HA_API_KEY")

# Convert 16-char hex string to C byte array (8 bytes)
hex_to_c_array_8() {
    local hex="${1//0x/}"
    local result=""
    for i in $(seq 0 2 14); do
        [[ -n "$result" ]] && result="${result}, "
        result="${result}0x${hex:$i:2}"
    done
    echo "$result"
}

# Convert 32-char hex string to C byte array (16 bytes)
hex_to_c_array_16() {
    local hex="${1//0x/}"
    local result=""
    for i in $(seq 0 2 30); do
        [[ -n "$result" ]] && result="${result}, "
        result="${result}0x${hex:$i:2}"
    done
    echo "$result"
}

EXT_PAN_C=$(hex_to_c_array_8 "$EXT_PAN_ID_HEX")
NET_KEY_C=$(hex_to_c_array_16 "$NETWORK_KEY_HEX")

cat > "$OUT_FILE" <<EOF
#ifndef THREAD_AUTH_H
#define THREAD_AUTH_H

/* Auto-generated by scripts/decrypt_secrets.sh — DO NOT EDIT. */

#define THREAD_NETWORK_NAME   "${NETWORK_NAME}"
#define THREAD_CHANNEL        ${CHANNEL}
#define THREAD_PAN_ID         ${PAN_ID}

static const uint8_t THREAD_EXT_PAN_ID[8] = {
    ${EXT_PAN_C}
};

static const uint8_t THREAD_NETWORK_KEY[16] = {
    ${NET_KEY_C}
};

#define THREAD_MESH_LOCAL_PREFIX  "${MESH_LOCAL_PREFIX}"
#define THREAD_HA_BASE_URL        "${HA_BASE_URL}"
#define THREAD_HA_API_KEY         "${HA_API_KEY}"

#endif /* THREAD_AUTH_H */
EOF

echo "Generated $OUT_FILE"
